// <auto-generated />
using KishanKumarDas_Assignment2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KishanKumarDas_Assignment2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KishanKumarDas_Assignment2.Models.Category", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = "general",
                            Name = "General"
                        },
                        new
                        {
                            CategoryId = "history",
                            Name = "History"
                        });
                });

            modelBuilder.Entity("KishanKumarDas_Assignment2.Models.Faq", b =>
                {
                    b.Property<int>("FaqId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FaqId"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TopicId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("FaqId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TopicId");

                    b.ToTable("Faqs");

                    b.HasData(
                        new
                        {
                            FaqId = 1,
                            Answer = "A CSS framework for creating responsive web apps for multiple screen sizes.",
                            CategoryId = "general",
                            Question = "What is Bootstrap?",
                            TopicId = "bootstrap"
                        },
                        new
                        {
                            FaqId = 2,
                            Answer = "A general purpose object oriented language that uses a concise, Java-like syntax.",
                            CategoryId = "general",
                            Question = "What is C#?",
                            TopicId = "csharp"
                        },
                        new
                        {
                            FaqId = 3,
                            Answer = "A general purpose scripting language that executes in a web browser.",
                            CategoryId = "general",
                            Question = "What is JavaScript?",
                            TopicId = "javascript"
                        },
                        new
                        {
                            FaqId = 4,
                            Answer = "In 2011.",
                            CategoryId = "history",
                            Question = "When was Bootstrap first released?",
                            TopicId = "bootstrap"
                        },
                        new
                        {
                            FaqId = 5,
                            Answer = "In 2002.",
                            CategoryId = "history",
                            Question = "When was C# first released?",
                            TopicId = "csharp"
                        },
                        new
                        {
                            FaqId = 6,
                            Answer = "In 1995",
                            CategoryId = "history",
                            Question = "When was JavaScript first released?",
                            TopicId = "javascript"
                        });
                });

            modelBuilder.Entity("KishanKumarDas_Assignment2.Models.Topic", b =>
                {
                    b.Property<string>("TopicId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TopicId");

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            TopicId = "bootstrap",
                            Name = "Bootstrap"
                        },
                        new
                        {
                            TopicId = "csharp",
                            Name = "C#"
                        },
                        new
                        {
                            TopicId = "javascript",
                            Name = "JavaScript"
                        });
                });

            modelBuilder.Entity("KishanKumarDas_Assignment2.Models.Faq", b =>
                {
                    b.HasOne("KishanKumarDas_Assignment2.Models.Category", "Category")
                        .WithMany("Faqs")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KishanKumarDas_Assignment2.Models.Topic", "Topic")
                        .WithMany("Faqs")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("KishanKumarDas_Assignment2.Models.Category", b =>
                {
                    b.Navigation("Faqs");
                });

            modelBuilder.Entity("KishanKumarDas_Assignment2.Models.Topic", b =>
                {
                    b.Navigation("Faqs");
                });
#pragma warning restore 612, 618
        }
    }
}
